language: node_js
node_js:
- stable
- '7'
- '6'
script:
- npm run build
- npm test
after_success:
- npm run coveralls
- git config user.email "mail@pepebecker.com"
- git config user.name "Pepe Becker"
- npm version patch
- git remote rm origin
- git remote add origin https://${GH_TOKEN}@github.com/pepebecker/find-hanzi.git
- git push --quiet --set-upstream origin master
deploy:
  provider: npm
  email: mail@pepebecker.com
  api_key:
    secure: GHXiAFJO0b0Yd64hfb1sjZhnjv4O/vJRkQO8xood36+Jn5CqChjw7hbsGEksIby/JV2Dnop9H68O6KV2Ef4unv53XPVIQgUPixY32jKClpWPph4nBoYjOtmzdncp7LcUVY6lyrW0H2erCuayECHnE+S7WYr821uoB2FXJIwoH1G720TUztmqNXCS6tqeTmU8wWCLwAVYR9usYuJL0FzXZgHGw8QZmpFgY3x3bY52H/MgVi11RlZW9AKyViVj5vb2Tb5L+ylN/mSPHTBazoxDMDqtdf0lm/I8cfNv94vO+ME7/3qOo9PULlr3bRxLfV0B6xwKgfiieE+7hSfyCXfsU+nz/Ay2np0r4QKHl5Z5ZhSjZySoHu/0EH2b+IpC1PdMGvzivD3qdBliuiqAyUu8/xgxjRYnxv4qqTHjNX5Ci7zKR4CQ6HGYKzh/8FMOjur4XhtmjFqZFqeEaiq1MVmUzdjUbxp8lRgOGKVEuBo4EYdGErGDzAu7cimL3QNUhJnqXQQX+QRpqvrtcPXv014Gwz/wkHKh/Xgoze1eVvlLjXcouu2zCNRehRpIkq2FkJQUrnDgfE0O2ntUY2NNa4gELzL+FHM7WOfwId5AKN6YnWioG3KvYF47sruU/KeFfm5S7XFHPGSPpD/FYBayT2B3eIoI9P9+8NrLst/sIHHNxVc=
  skip_cleanup: true
  on:
    branch: master
    node: stable
env:
  global:
    secure: TqtnqGjAjSY4y8q+wtE56IfU+OBvIlJKb6fbfBtJp2v2r3VO0XjS6fVVn/xhEMDRu/aBRQ11RC1EHRTdhZ1oO9AXXJE4p3l1oazneOJOUkyXniG8sfT67EjUoWcWH7IX5GzqIHmlEst/55Mvjkw1qwJGzH25mnWHgHBDZeWZgEX6dB/+P7+/RZA2wwlD+LMK9EQjYzJZiqY1bmogRDvqWf7pyGp8OAFsSszKoCDRwxKbpSYevHp0oKaaxwgZ9MC/J2ONP7OObjy/hzXXm4UuqKBFdk4R1kkG5R5w9FkO6skYQzHvOIikrEpoBAtVnAJEYzt3zt0ouNmg/FbKutkUb9A2e+rsVQ4De1grBCI13FZ90wT3lmbApzCKWjsyODczoWiR1lLwCJANCepLYMcxwnN0qFpxb2qpO5AgYFzigw+5cVBCjh6OPFsf/3CeWmYWj1GBtPqZEQeGJe3sXtgAVvSScUBe5llLSue79U+9ujqh7vlJLvBzPgm5WNoFndhtbgcc0Iqs3zarHPyNNGMYjtZEQD8Wu2SjiRy0fHgQn64QgbToeXdLoVhxG2045obllquNi/lH0zfb6Cv2VKzFatNy8tpHdDvt1MatTe2zjALAa0MGx4IaQyiltad/sY1bW+0lJ6Ow10SK4GM7CwxckeC9cHaYWkYZL1HKt3EZgMI=
