language: node_js
node_js:
  - "stable"
  - "7"
  - "6"
script:
  - npm run build
  - npm test
after_success:
  - npm run coveralls
  - npm version patch
deploy:
  provider: npm
  skip_cleanup: true
  email: "mail@pepebecker.com"
  api_key: $TRAVIS_API_KEY
  on:
    branch: master
    node: latest